-- AlterTable
ALTER TABLE "interview_sessions" 
  ADD COLUMN IF NOT EXISTS "totalQuestions" INTEGER NOT NULL DEFAULT 5,
  ADD COLUMN IF NOT EXISTS "currentQuestionNo" INTEGER NOT NULL DEFAULT 1,
  ALTER COLUMN "status" SET DEFAULT 'ACTIVE',
  ALTER COLUMN "startedAt" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "questions" 
  ADD COLUMN IF NOT EXISTS "isFollowUp" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "parentQId" TEXT;
