import { PDFParse } from "pdf-parse";
import { GoogleGenAI } from "@google/genai";

const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });

export async function parsePDF(buffer: Buffer): Promise<string> {
    try {
        const parser = new PDFParse({ data: buffer });
        const result = await parser.getText();
        await parser.destroy();
        return result.text;
    } catch (error) {
        console.error("PDF Parsing Error:", error);
        throw new Error("Failed to extract text from PDF");
    }
}

export async function parseResumeWithAI(resumeTxt: string) {
    const prompt = `Parse the following resume text and extract the information requested. Respond STRICTLY in valid JSON format with no markdown wrappers or backticks.

    Resume Text:
    ${resumeTxt}
    
    Expected JSON format:
    {
      "name": "Candidate Name",
      "title": "Professional Title / Role",
      "aiSummary": "Comprehensive summary of the candidate's background",
      "contact": {
        "email": "email@example.com",
        "phone": "+1...",
        "location": "City, Country",
        "linkedin": "linkedin url"
      },
      "skills": ["skill1", "skill2"],
      "experience": [
        {
          "company": "Company",
          "title": "Role Title",
          "dates": "Date range",
          "location": "Location",
          "responsibilities": ["bullet 1", "bullet 2"]
        }
      ],
      "education": [
        {
          "institution": "University/College",
          "degree": "Degree/Major",
          "year": "Graduation Year"
        }
      ],
      "projects": [
         {
            "name": "Project Name",
            "description": "Project details"
         }
      ],
      "certifications": ["Cert 1"]
    }`;

    try {
        const response = await ai.models.generateContent({
            model: "gemini-3.5-flash-lite",
            contents: prompt,
            config: {
                responseMimeType: "application/json",
            }
        });

        const responseText = response.text;
        if (!responseText) {
            throw new Error("No text content generated by AI model");
        }

        const cleanJson = responseText.replace(/```json/gi, '').replace(/```/g, '').trim();
        return JSON.parse(cleanJson);
    } catch (error) {
        console.error("AI Parsing Error:", error);
        throw new Error("Failed to extract structured data using AI");
    }
}