import { GoogleGenAI } from "@google/genai";
import { z } from "zod";

const ai = new GoogleGenAI({
    apiKey: process.env.GEMINI_API_KEY,
});

const QuestionSchema = z.object({
    questionNo: z.number(),
    questionText: z.string(),
    questionType: z.enum(["BEHAVIORAL", "CODING", "TECHNICAL", "MIXED"]),
});

const GeneratedQuestionsSchema = z.array(QuestionSchema);

export async function generateQuestionWithAI(
    resumeText: string,
    jobDescriptionText: string,
    difficultyLevel: string = "MEDIUM",
    NoOfQuestions: number = 10
) {
    const prompt = `
    Generate a list of ${NoOfQuestions} interview questions based on the provided resume and job description.
    The questions should be relevant to the candidate's experience and the requirements of the job.
    
    Resume Context:
    ${resumeText}
    
    Job Description Context:
    ${jobDescriptionText}

    Difficulty Level: ${difficultyLevel}
    
    Return the questions STRICTLY in the following JSON array format with no markdown wrappers:
    [
        {
            "questionNo": 1,
            "questionText": "Question text here...",
            "questionType": "BEHAVIORAL"
        },
        {
            "questionNo": 2,
            "questionText": "Question text here...",
            "questionType": "TECHNICAL"
        }
    ]
    `;

    try {
        const response = await ai.models.generateContent({
            model: "gemini-3.5-flash-lite",
            contents: prompt,
            config: {
                responseMimeType: "application/json",
            }
        });

        const responseText = response.text;
        if (!responseText) {
            throw new Error("No text content generated by AI model");
        }

        const cleanJson = responseText.replace(/```json/gi, '').replace(/```/g, '').trim();
        const rawJson = JSON.parse(cleanJson);

        return GeneratedQuestionsSchema.parse(rawJson);
    } catch (error) {
        console.error("AI Question Generation Error:", error);
        throw new Error("Failed to generate questions using AI");
    }
}

export default {
    generateQuestionWithAI,
};